Change function name from uv3d to main
The function name "uv3d" triggered ImportError: cannot import name 'main' from 'bdschism.uv3d' when the function uv3d was called in command line.